---

- name: create vm
  shell: |
    virt-install \
      --memory "{{ item.0.ram }}" \
      --vcpus "{{ item.0.vcpu }}" \
      --name "{{ item.0.name }}{{ '{0:02d}'.format( item.1 ) }}" \
      --disk /var/lib/libvirt/images/{{ item.0.name + '{0:02d}'.format( item.1 ) }}_{{ item.0.os_variant }}.qcow2,device=disk,bus=virtio,format=qcow2 \
      --disk /var/lib/libvirt/cloud_init/{{ item.0.name + '{0:02d}'.format( item.1 ) }}/{{ item.0.name + '{0:02d}'.format( item.1 ) }}.iso,device=cdrom \
      --os-variant "{{ item.0.os_variant }}" \
      --virt-type kvm \
      --graphics=none \
      --console=none \
      --network network="{{ item.0.network }}" \
      --import
  when: "item.0.name + '{0:02d}'.format( item.1 ) in create_vms"
  loop: "{{ server_roles | subelements('count') }}"
