---
- name: Add Kubernetes repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    enabled: true
    gpgcheck: true
    exclude: kubelet kubeadm kubectl

- name: Install packages
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: true
  loop: "{{ packages_list }}"
  

- name: Install k8s packages
  yum:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
    disable_excludes: all
  loop: "{{ kubernetes_package_list }}"