---
- name: Deploy KVM Infraestructure
  hosts: kvm_hosts
  vars_files: ./vars/vars.yml
  vars:
    create_vms: []
  become: yes
  tasks:
    - name: Install virtualization packages
      block:
        - name: Install packages
          import_tasks: tasks/install_packages.yml
    - name: Create networks
      block:
        - name: Manage virsh networks
          import_tasks: tasks/create_network.yml
      
    - name: Validate status of Infra
      block:
        - name: Get VM info
          import_tasks: tasks/validate_vm_exists.yml

    - name: Create cloud images
      block:
        - name: Download operative systems ISO
          import_tasks: tasks/cloud_images.yml 
        - name: Create cloud init config
          import_tasks: tasks/cloud_init.yml

    - name: Create virtual infra
      block:
        - name: Create virtual machines
          import_tasks: tasks/create_vm.yml
